create components, add eslint rule, and edit reset.css
react-challengers/Codefolio pull request #16
Opened 2023-02-10 10:06 UTC by nno3onn

## What is this PR? :mag:

- reset.css 파일을 수정하였습니다.
- 페이지에서 사용되는 버튼(DefaultButton) 컴포넌트를 구현하였습니다.
- 레이아웃에서 사용되는 GNB 컴포넌트를 구현하였습니다.
- eslint 룰을 추가하였습니다.

## branch

- chore/resetCss -> dev

## Changes :memo:

-body에 box-sizing: border-box 을 추가하였습니다.
- eslint 룰에서 @typescript-eslint/no-use-before-define 를 꺼놓았습니다.
- DefaultButton, GNB 컴포넌트를 구현하였습니다.

(이슈 번호를 여기 입력 해 주세요.) by @nno3onn

2023-02-10 10:23 UTC, Jeremy-Kr requested changes
리뷰 확인 부탁드립니다!

2023-02-10 10:23 UTC, Jeremy-Kr commented on pages/index.tsx
>    );
테스트용 코드는 삭제 부탁드립니다!

2023-02-10 10:23 UTC, Jeremy-Kr commented on Components/Layouts/GNB.tsx
> +          <Image src="/icons/person.svg" alt="" width="24" height="24" />
이미지를 설명하는 alt text를 작성 부탁드립니다!

2023-02-10 10:35 UTC, Jeremy-Kr approved these changes
LGTM

2023-02-10 10:36 UTC, hyoloui approved these changes
고생 많으셨습니다!! 정익님이 미리 피드백 주셔서 이하동문 입니다

2023-02-10 10:40 UTC, arch-spatula reviewed
[메인/Vector.png](https://github.com/react-challengers/Codefolio/pull/16/files#diff-5155623a37c725f37dab9d38cfd2000fb64a8a39f47d5977eaab6df98e2bf172)

svg도 이미 있는데 png를 추가한 이유가 있나요?

2023-02-10 10:40 UTC, arch-spatula commented on pages/index.tsx
> +import GNB from "@/Components/Layouts/GNB";
`_app.tsx`로 이동시켜주시기 바랍니다.

2023-02-10 10:40 UTC, yunjunhojj approved these changes
확인했습니다.

2023-02-10 10:42 UTC, arch-spatula approved these changes

2023-02-10 10:43 UTC, merged

2023-02-13 00:07 UTC, arch-spatula commented on Components/Common/DefaultButton.tsx
> +` as any;
any 문서화 혹은 이슈화