Feat/profile phone number and year
react-challengers/Codefolio pull request #189
Opened 2023-02-21 13:59 UTC by arch-spatula

## What is this PR? :mag:

- query hook 조기 리팩토링

## branch

- feat/ProfilePhoneNumber -> dev

## Changes :memo:

-

(#173 ) by @arch-spatula 

![스크린샷 2023-02-21 오후 10 58 12](https://user-images.githubusercontent.com/84452145/220365356-fe805700-7394-4441-bc02-0c6c07f6b4a8.png)

2023-02-21 14:29 UTC, hyoloui approved these changes

2023-02-21 14:29 UTC, hyoloui commented on hooks/query/useUserProfile.ts
> +    phone: data?.phone ?? "01000000000",
default 값 팀원분들이랑 고민 해보면 좋을 것 같아요

2023-02-22 00:31 UTC, yunjunhojj commented on Components/MyPage/EditProfileContainer.tsx
>  const fieldList = [
요놈들 사용하시는건가요?

2023-02-22 00:31 UTC, yunjunhojj commented on Components/MyPage/EditProfileContainer.tsx
> +  // setIsPhoneNumber(checkIsPhoneNumber(inputValues.phoneNumber));
이런 주석들은 추후 리팩토링하려고 남겨두신 건가요? (궁금해서)

2023-02-22 00:35 UTC, arch-spatula commented on Components/MyPage/EditProfileContainer.tsx
>  const fieldList = [
주석처리했습니다

2023-02-22 00:36 UTC, arch-spatula commented on Components/MyPage/EditProfileContainer.tsx
> +  // setIsPhoneNumber(checkIsPhoneNumber(inputValues.phoneNumber));
리팩토링을 위해 남겼습니다

2023-02-22 01:44 UTC, Jeremy-Kr requested changes

2023-02-22 01:44 UTC, Jeremy-Kr commented on Components/Common/DropDown.tsx
> +  // ]);
주석삭제

2023-02-22 01:44 UTC, Jeremy-Kr commented on Components/Common/DropDown.tsx
> +    setCareer(profileData.career);
profileData가 undefined일때 처리 부탁드려요

2023-02-22 01:44 UTC, Jeremy-Kr commented on Components/Common/DropDown.tsx
> +  }, []);
profileData 디펜던시 어레이 추가

2023-02-22 01:44 UTC, Jeremy-Kr commented on Components/MyPage/EditProfileContainer.tsx
> +
data들이 undefined 일 때 처리

2023-02-22 01:44 UTC, Jeremy-Kr commented on hooks/query/useUserProfile.ts
> +      console.log(newProfile);
콘솔

2023-02-22 01:44 UTC, Jeremy-Kr commented on hooks/query/useUserProfile.ts
>   * @see https://tanstack.com/query/v4/docs/react/guides/optimistic-updates
5버전 docs 참고

2023-02-22 01:44 UTC, Jeremy-Kr commented on Components/MyPage/ShowProfileContainer.tsx
> +              <p>{profileData.career}</p>
옵셔널 체이닝

2023-02-22 01:44 UTC, Jeremy-Kr commented on Components/MyPage/SwitchButton.tsx
> +  }, []);
profileData가 없을 때 처리

2023-02-22 01:44 UTC, Jeremy-Kr commented on Components/MyPage/UserInfoContainer.tsx
> +      <Banner userBackground={inputValues.backgroundColor} />
옵셔널체이닝 or nullish 처리

2023-02-22 01:44 UTC, Jeremy-Kr commented on Components/MyPage/UserInfoContainer.tsx
> +                onChange={handleInputChange("selfProfile")}
익명함수로 변경
```tsx
() => {
  handleInputChange("selfProfile")
}
```

2023-02-22 01:44 UTC, Jeremy-Kr commented on Components/MyPage/UserInfoContainer.tsx
> +                  onChange={handleInputChange("backgroundColor")}
익명함수로 변경

2023-02-22 01:44 UTC, Jeremy-Kr commented on Components/MyPage/UserInfoContainer.tsx
> +              <SelfProfileWrapper>{inputValues.selfProfile}</SelfProfileWrapper>
옵셔널 체이닝

2023-02-22 02:01 UTC, arch-spatula commented on Components/MyPage/UserInfoContainer.tsx
> +                onChange={handleInputChange("selfProfile")}
```ts
const handleInputChange = (field: string) => {
    return (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
      setInputValues((prev) => ({
        ...prev,
        [field]: e.target.value,
      }));
    };
  };
```

이런 구조라 익명함수로 한번 감싸면 동작하지 않습니다

2023-02-22 02:06 UTC, Jeremy-Kr approved these changes

2023-02-22 02:08 UTC, nno3onn approved these changes

2023-02-22 02:10 UTC, yunjunhojj approved these changes
Good

2023-02-22 02:16 UTC, hyoloui approved these changes

2023-02-22 02:16 UTC, merged