Feat/project info 컴포넌트 구성
react-challengers/Codefolio pull request #28
Opened 2023-02-10 16:56 UTC by yunjunhojj

## What is this PR? :mag:
Feat/project info 컴포넌트 구성 
-

## branch

- feat/ -> dev

## Changes :memo:
초기 pr 입니다 
-

(이슈 번호를 여기 입력 해 주세요.) by #8

2023-02-10 17:01 UTC, hyoloui requested changes

2023-02-10 17:01 UTC, hyoloui commented on Components/Common/ProjectInfoDropDown.tsx
> +  border: 0rem;
`border : none;` 적용이 좋지 않나용?

2023-02-10 23:20 UTC, Jeremy-Kr requested changes
리뷰 확인 부탁드려용

2023-02-10 23:20 UTC, Jeremy-Kr commented on Components/Common/ProjectInfo.tsx
> +      {openDropdown ? <ProjectInfoDropDown></ProjectInfoDropDown> : null}
```
openDropdown && <ProjectInfoDropDown />}
```
로 수정 가능할 것 같습니다.

2023-02-10 23:20 UTC, Jeremy-Kr commented on Components/Common/ProjectInfo.tsx
> +        <DropdownButton onClick={() => setOpenDropdown(!openDropdown)}>
사용자가 드롭다운을 빠르게 연속으로 클릭할 시에도 값을 보장하기 위해 디바운싱, 쓰로틀링을 적용하기 전
```
setOpenDropdown((prev)=> !prev)
```
로 변경하는건 어떨까요?

2023-02-10 23:20 UTC, Jeremy-Kr commented on Components/Common/ProjectInfo.tsx
> +  border: 0rem;
border: none

2023-02-10 23:20 UTC, Jeremy-Kr commented on Components/Common/ProjectInfoDropDown.tsx
> +  border: 0.0625rem solid #cccccc;
1px이 더 좋아보입니다

2023-02-10 23:20 UTC, Jeremy-Kr commented on Components/Common/ProjectInfoDropDown.tsx
> +  border-bottom: 0.0625rem solid;
1픽셀이 더 좋아보입니다.

2023-02-14 00:36 UTC, arch-spatula requested changes
정익님 승효님 의견 반영돠면 Approve하겠습니다.

2023-02-14 00:52 UTC, Jeremy-Kr approved these changes

2023-02-14 01:47 UTC, nno3onn approved these changes

2023-02-14 05:18 UTC, arch-spatula approved these changes

2023-02-14 05:18 UTC, merged