Fix/Image-file-name
react-challengers/Codefolio pull request #286
Opened 2023-03-04 12:35 UTC by hyoloui

## What is this PR? :mag:

- 한글이름 에러 해결
- 썸네일 파일 유효성 검사 후 return

## branch

- fix/Image-file-name -> dev

## Changes :memo:

- uri 에 추가되는 file.name 삭제
- 정규표현식 수정
- image src = post.title_background_image 로 수정

(#273) by @hyoloui

2023-03-04 12:58 UTC, Jeremy-Kr requested changes

2023-03-04 12:58 UTC, Jeremy-Kr commented on Components/CreatePost/Post/Post.tsx
> +
이런식으로 썸네일을 저장하는 것 보다, isThumbnail이라는 컬럼을 하나 추가해서 썸네일을 불러오는게 이상적인 방법일 것 같아요!

2023-03-04 12:58 UTC, Jeremy-Kr commented on utils/card/findThumbnailInContent.ts
> +    return result[0].replace("/thumbnail", "");
이렇게 되면 isThumbnail을 체크 안했을 시,
content에서 첫번째 사진을 찾아서 가져올 수 있는 로직을 사용할 수 없게 될 것 같아요!

2023-03-04 13:10 UTC, hyoloui commented on Components/CreatePost/Post/Post.tsx
> +
네 그렇게도 생각 해 봤는데 다시 생각해보니 말씀하신 방법이 더 좋겠네요!
그럼 column 추가 하겠습니다!

2023-03-05 01:05 UTC, Jeremy-Kr requested changes

2023-03-05 01:05 UTC, Jeremy-Kr commented on Components/CreatePost/Post/Post.tsx
> +    setIsThumbnail("");
왜 bool이 아니라 string인가요?

2023-03-05 01:05 UTC, Jeremy-Kr commented on Components/CreatePost/Post/Post.tsx
> +      setIsThumbnail(titleBackgroundImage);
!!titleBackgroundImage 같은 느낌으로 bool로 넣어주어야 하지 않을까요?

2023-03-05 04:06 UTC, nno3onn approved these changes

2023-03-05 04:06 UTC, nno3onn commented on Components/CreatePost/Post/PostTitle.tsx
> +        const fileId = `${uuidv4()}`;
uuidv4() 로 작성해도 될 것 같아요

2023-03-05 07:01 UTC, hyoloui commented on Components/CreatePost/Post/Post.tsx
> +    setIsThumbnail("");
수정했습니다
원래는 체크 상태 확인해서 칼럼에도 주소를 같이 넣어주는 방식이였는데,

비효율적인 것 같아서 체크 상태만 넣어주고
썸네일을 받아 올 때 해당 칼럼 boolean 확인만 하면 되게끔 @Jeremy-Kr

2023-03-05 07:35 UTC, Jeremy-Kr requested changes

2023-03-05 07:35 UTC, Jeremy-Kr commented on Components/MyPage/CardItemContainer.tsx
> +              )}
post.thumbnail_check ? 로 단순화 할 수 있지 않을까요?

2023-03-05 07:35 UTC, Jeremy-Kr commented on Components/Main/MainSection.tsx
> +              )}
post.thumbnail_check ? 로 단순화 할 수 있지 않을까요?

2023-03-05 07:35 UTC, Jeremy-Kr commented on Components/Detail/RelatedProject/RelatedProject.tsx
> +                      )}
post.thumbnail_check ? 로 단순화 할 수 있지 않을까요?

2023-03-06 00:59 UTC, Jeremy-Kr approved these changes

2023-03-06 00:59 UTC, merged