Feat/user page
react-challengers/Codefolio pull request #309
Opened 2023-03-06 10:30 UTC by nno3onn

## What is this PR? :mag:

- 프로필 페이지 칭찬배지 탭 구현

<img width="894" alt="image" src="https://user-images.githubusercontent.com/60952506/223084974-8d4da173-cb80-4fc9-a279-ce7a238d3695.png">

## branch

- feat/UserPage -> dev

## Changes :memo:
- 프로필 페이지 칭찬배지
- 프로필 페이지 댓글 CRUD

(이슈 번호를 여기 입력 해 주세요.) by @nno3onn

2023-03-06 11:24 UTC, Jeremy-Kr requested changes

2023-03-06 11:24 UTC, Jeremy-Kr commented on Components/MyPage/TabProfile/GoodJobBadge.tsx
> +        setToolNum(tool);
추후에 comment나 bookmark, like등의 방식대로 table에 count를 추가해주는건 어떨까요?

2023-03-06 11:24 UTC, Jeremy-Kr commented on Components/MyPage/TabProfile/ProfileComment.tsx
> +  if (isLoading) return <>loading...</>;
좋은 의견 같아요

2023-03-06 11:24 UTC, Jeremy-Kr commented on utils/APIs/supabase/postProfileComment.ts
> + *   }
일치하지 않는 주석같아요

2023-03-06 11:46 UTC, nno3onn commented on Components/MyPage/TabProfile/GoodJobBadge.tsx
> +        const badgeList = data.map((v) => v.type);
ㅣ네 수정하겠습니다 ㅎㅎ

2023-03-06 12:46 UTC, hyoloui approved these changes
피드백 반영 되면 LGTM 입니다!

2023-03-07 00:04 UTC, Jeremy-Kr approved these changes

2023-03-07 00:04 UTC, merged