refactor: DropDown.tsx
react-challengers/Codefolio pull request #33
Opened 2023-02-11 00:00 UTC by hyoloui

- 불친절한 드롭다운 리펙토링
- 추후 스타일링 필요

#8

## What is this PR? :mag:

- 친절한 드롭다운으로 리펙토링

## branch

- feat/DropDown -> dev

## Changes :memo:

- 사용할 컴포넌트, 페이지에서 data="(ex: 회원가입)" 작성시 셀렉트 자동 완성로직 구현

(#8) by @hyoloui

2023-02-11 01:14 UTC, Jeremy-Kr requested changes
리뷰 확인 부탁드립니다.

2023-02-11 01:14 UTC, Jeremy-Kr commented on Components/Common/DropDown.tsx
> +  data: ComponenetData;
data라는 이름보다 `type`이 더 적절한 것 같은데 어떻게 생각하시나요?

2023-02-11 01:14 UTC, Jeremy-Kr commented on Components/Common/DropDown.tsx
> +        <option key={option} value={option} defaultValue={option}>
defaultValue의 역할이 무엇인가요? 제 생각에는 Select에 들어가는게 적절해 보여요!

2023-02-14 00:39 UTC, arch-spatula requested changes

2023-02-14 00:39 UTC, arch-spatula commented on Components/Common/DropDown.tsx
> +  );
`1950`은 무슨의미가 있나요? 의미가 있다면 상수로 변경해주시기 바랍니다

2023-02-14 01:01 UTC, yunjunhojj approved these changes

2023-02-14 02:10 UTC, nno3onn approved these changes

2023-02-14 02:10 UTC, nno3onn commented on Components/Common/DropDown.tsx
> +  data: ComponenetType;
data보다는 type이 더 직관적일 것 같아요!

2023-02-14 05:24 UTC, arch-spatula approved these changes

2023-02-14 05:29 UTC, Jeremy-Kr commented
test

2023-02-14 05:53 UTC, merged