Feat/loginpage
react-challengers/Codefolio pull request #35
Opened 2023-02-11 00:29 UTC by yunjunhojj

## What is this PR? :mag:

- 로그인 및 회원가입 페이지 구현 했습니다. 기본적인 동작 확인만했습니다.
- 추후에 에러 관리 및 유효성 검사가 필요한 부분입니다.

## branch

- feat/ -> dev

## Changes :memo:

- 초기 커밋입니다. 내용은 위와 동일합니다. 

#6 by @yunjunhojj

2023-02-11 00:43 UTC, arch-spatula commented on pages/auth/login.tsx
> +  margin-top: 30px;
px -> rem

2023-02-11 00:43 UTC, arch-spatula commented on pages/auth/login.tsx
> +  }
화살표함수로 수정해주시기 바랍니다

2023-02-11 00:43 UTC, arch-spatula commented on pages/auth/login.tsx
> +  margin-top: 10px;
px -> rem

2023-02-11 00:43 UTC, arch-spatula commented on pages/auth/login.tsx
TODO 문서화 추가부탁합니다. 네이버, 카카오 로그인 연결하기

2023-02-11 00:43 UTC, arch-spatula commented on pages/auth/signup.tsx
> +  const [passwordCheck, setPasswordCheck] = useState("");
useTextInput custom hook 누가할지 정해지면 리팩토링 부탁드립니다.

2023-02-11 00:43 UTC, arch-spatula commented on pages/auth/signup.tsx
> +  height: 55px;
px -> rem

2023-02-11 00:43 UTC, arch-spatula commented on pages/auth/signup.tsx
> +`;
px -> rem

2023-02-13 08:31 UTC, yunjunhojj commented on pages/auth/login.tsx
> +  }
넵 기능 확인차 기본 함수로 진행했습니다. 변경 예정입니다 감사합니다~

2023-02-14 00:56 UTC, Jeremy-Kr reviewed
상현님 리뷰 완료되면 어프로프 하겠습니다.

2023-02-15 01:23 UTC, arch-spatula approved these changes

2023-02-15 01:39 UTC, Jeremy-Kr requested changes

2023-02-15 01:39 UTC, Jeremy-Kr commented on pages/auth/login.tsx
> +          <LoginButton>네이버로 로그인하기</LoginButton>
요기도 주석처리하는게 어떨까요?

2023-02-15 08:21 UTC, hyoloui approved these changes

2023-02-15 08:40 UTC, arch-spatula approved these changes

2023-02-15 08:45 UTC, nno3onn approved these changes

2023-02-15 08:45 UTC, Jeremy-Kr approved these changes

2023-02-15 08:45 UTC, merged