Feature/mypage 마이페이지 구현
react-challengers/Codefolio pull request #40
Opened 2023-02-13 12:35 UTC by nno3onn

## What is this PR? :mag:

- 마이페이지 화면 및 수정 화면을 구현하였습니다.
![Feb-13-2023 21-31-18](https://user-images.githubusercontent.com/60952506/218459132-9744ea8c-ece9-4981-afe7-1ed589115310.gif)

## branch

- feat/Mypage -> dev

## Changes :memo:

수정 페이지
- 성별 - 스위치 버튼
- 출생년도 - 드롭다운 (범위: 최근 년도부터 50년까지)
- 휴대전화 - 인풋창
- 포지션 - On/Off 버튼
- 경력 - 드롭다운 (범위: 1~20년)
- 스킬: 추가하는 인풋 및 버튼
- 프로필 공개여부 - 토글

#4 by @nno3onn

2023-02-13 13:49 UTC, arch-spatula commented on tsconfig.json
> +    "downlevelIteration": true,
설명부탁드립니다

2023-02-13 13:49 UTC, arch-spatula commented on Components/MyPage/ShowProfileContainer.tsx
> +        </ProfileContainer>
여기 fragment는 가독성을 위해 두셨나요?

2023-02-13 13:49 UTC, arch-spatula commented on Components/MyPage/EditProfileContainer.tsx
> +  };
@TODO useinput 문서화 추가해주시기 바랍니다

2023-02-13 13:52 UTC, nno3onn commented on tsconfig.json
> +    "downlevelIteration": true,
https://points.tistory.com/106
다음과 같은 문제가 발생하여 해결하기 위해 추가한 코드입니다.

2023-02-13 13:54 UTC, nno3onn commented on Components/MyPage/SkillList.tsx
> +  );
불필요해보입니다. 제거하겠습니다 :)

2023-02-13 13:56 UTC, nno3onn commented on Components/MyPage/ShowProfileContainer.tsx
> +        </ProfileContainer>
ProfileContainer 컴포넌트가 children(type: ReactElement)를 props로 받아오기 때문에 추가한 fragment입니다.

2023-02-14 00:44 UTC, nno3onn commented on .eslintrc.json
> +    "@typescript-eslint/naming-convention": 0,
1. "react/no-array-index-key": 0,
skillList.tsx파일의 line25에서 editSkills는 배열 마지막에 값이 추가되는 형태이기 때문에  key값을 Idx로 주는 것이 효율적이다 생각이 들어 룰을 추가하였습니다.

2. "react/jsx-no-useless-fragment": 0,
아래 피드백으로 인해 fragment가 불필요해졌으므로 해당 룰을 제거하였습니다.

3. "@typescript-eslint/naming-convention": 0,
db에 snake_case 형태인 값들을 바로 가져오고자 추가하게된 룰입니다. 하지만 destructuring 할 때 굳이 네이밍을 바로 가져오지 않고 이름을 변경하면 되어도 괜찮다는 생각이 들어서 현재 코드를 수정하였습니다.
```
  const {
    gender,
    birth_year: birthYear,
    phone,
    skills,
    careerer,
    is_public: isPublic,
  } = userInfo;
```

2023-02-14 00:50 UTC, Jeremy-Kr requested changes
리뷰 늦어서 죄송합니다! 확인 부탁드려요

2023-02-14 00:50 UTC, Jeremy-Kr commented on Components/MyPage/CardItemContainer.tsx
> +// const CardItemContainer = ({ itemList }: PostType[]) => {
이 주석은 추후 사용하기 위함인가요?

2023-02-14 00:50 UTC, Jeremy-Kr commented on Components/MyPage/EditProfileContainer.tsx
> +      const newActiveField = activeField.filter((af) => af !== field);
af가 activeField인가요? `activeFieldItem` 으로 명확하게 변수명을 지정하는건 어떨까요?

2023-02-14 00:59 UTC, nno3onn commented on Components/MyPage/EditProfileContainer.tsx
> +      const newActiveField = activeField.filter((af) => af !== field);
넵

2023-02-14 01:09 UTC, nno3onn commented on Components/MyPage/EditProfileContainer.tsx
> +  };
useInput 커스텀훅 생성하였습니다!

2023-02-14 01:19 UTC, nno3onn commented on Components/MyPage/CardItemContainer.tsx
> +// const CardItemContainer = ({ itemList }: PostType[]) => {
db와 연결하는 과정에서 추후 사용하려고 하였으나, 확인해보니 db와 형태가 다른 점이 있어 해당 줄을 제거하였습니다.

2023-02-14 01:28 UTC, yunjunhojj approved these changes
이미 작성하신 두 튜터님...아니아니 정익님하고 상현님 내용 외에 추가 적인 내용은 딱히 없습니다.

2023-02-14 01:28 UTC, yunjunhojj commented on Components/MyPage/EditProfileContainer.tsx
> +  flex-direction: row;
flex-direction 의 기본 값이 row아닌가요? 안 써도 똑같은 스타일 이지 않을까 생각하는데. 혹시 이유가 있으시면 알려주세요! (질문입니다. ㅎㅎ )

2023-02-14 01:28 UTC, yunjunhojj commented on Components/MyPage/EditProfileContainer.tsx
> +  border: 0.0625rem solid lightgrey;
요놈은 그냥 1px로 저도 맨날 빼먹는 곳...하핳

2023-02-14 01:33 UTC, nno3onn commented on Components/MyPage/EditProfileContainer.tsx
> +  flex-direction: row;
확실하게 작성하는 것을 좋아해서.. 저는 작성하는 편입니다

2023-02-14 01:34 UTC, nno3onn commented on Components/MyPage/EditProfileContainer.tsx
> +  border: 0.0625rem solid lightgrey;
전체 적용하면서 같이 변경되었나봅니다 수정하겠습니다!

2023-02-14 05:55 UTC, merged